# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_orion
    ports:
      - 3308:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080